import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline"> Build hulu with nextJs</h1>
     {/* Header */}

     {/* Nav */}

     {/* Results */}

    </div>
  )
}
